import json
import re
import time
import httpx
from typing import Dict, Any, List, Optional
from config import settings
from memory import memory_bank
from automation import automation_engine
from tools import jarvis_tools

class AIEngine:
    """
    J.A.R.V.I.S. Mark II Artificial Intelligence & Complete Tool Dispatcher.
    Handles all 24 Agentic capabilities including Vision, Document Forge, Web Research,
    Desktop Control, Coding, Image Generation, and Multi-Engine LLMs.
    """
    def __init__(self):
        pass

    def process_message(self, user_message: str, engine_override: Optional[str] = None) -> Dict[str, Any]:
        engine_to_use = engine_override or settings.ACTIVE_ENGINE
        user_lower = user_message.strip().lower()

        # Step 1: Log user message
        memory_bank.log_message("user", user_message)

        executed_tools: List[Dict[str, Any]] = []
        memory_updates: List[Dict[str, Any]] = []

        # -- Tool 1: AI Image Generation ("generate image of ...", "draw image ...", "create image ...") --
        if any(w in user_lower for w in ["generate image", "draw image", "create image", "render image", "picture of"]):
            prompt_match = re.sub(r"^(generate|draw|create|render)\s+(an?\s+)?(ai\s+)?(image|picture|photo)\s+(of\s+)?", "", user_message, flags=re.IGNORECASE).strip()
            if not prompt_match:
                prompt_match = user_message
            img_res = jarvis_tools.generate_ai_image(prompt_match)
            executed_tools.append({"tool": "generate_ai_image", "result": img_res})

        # -- Tool 2: Document Generation ("generate docx", "make powerpoint", "create resume", "generate pptx", "excel xlsx") --
        elif any(w in user_lower for w in ["generate resume", "create resume", "generate docx", "make docx", "generate ppt", "make powerpoint", "generate excel", "make xlsx", "generate document", "create report"]):
            doc_type = "md"
            if "docx" in user_lower or "word" in user_lower or "resume" in user_lower:
                doc_type = "docx"
            elif "ppt" in user_lower or "powerpoint" in user_lower or "slide" in user_lower:
                doc_type = "pptx"
            elif "excel" in user_lower or "xlsx" in user_lower or "sheet" in user_lower:
                doc_type = "xlsx"
            title = re.sub(r"^(generate|make|create)\s+(a\s+|an\s+)?(docx|pptx|xlsx|ppt|excel|word|resume|report|document)\s+(on|about|for)?\s*", "", user_message, flags=re.IGNORECASE).strip()
            if not title:
                title = "Stark_Executive_Report"
            content = f"Executive Summary for {title}\n\n1. Overview & Objective: Comprehensive analysis generated by J.A.R.V.I.S. Mark II.\n\n2. Key Performance Indicators: Optimal efficiency across all metrics.\n\n3. Next Action Protocol: Immediate deployment and execution."
            doc_res = jarvis_tools.generate_document(doc_type, title, content)
            executed_tools.append({"tool": "generate_document", "result": doc_res})

        # -- Tool 3: Web Search & Research Report ("research report", "search web for", "web search") --
        elif any(w in user_lower for w in ["research report", "search web", "web search", "google search", "duckduckgo", "latest news on"]):
            query = re.sub(r"^(generate\s+)?(research\s+report|search\s+web|web\s+search|google\s+search|latest\s+news)\s+(on|about|for)?\s*", "", user_message, flags=re.IGNORECASE).strip()
            if not query:
                query = user_message
            res_report = jarvis_tools.web_search_research(query, generate_report="report" in user_lower)
            executed_tools.append({"tool": "web_search_research", "result": res_report})

        # -- Tool 4: Open/Close Apps ("open chrome", "close spotify", "launch vscode") --
        elif any(user_lower.startswith(prefix) for prefix in ["open ", "launch ", "start ", "close ", "kill ", "terminate "]) and any(app in user_lower for app in ["chrome", "browser", "firefox", "code", "vscode", "terminal", "calculator", "notepad", "spotify"]):
            words = user_lower.split()
            action = words[0]
            app = " ".join(words[1:])
            app_res = jarvis_tools.desktop_app_control(action, app)
            executed_tools.append({"tool": "desktop_app_control", "result": app_res})

        # -- Tool 5: Keyboard & Mouse Automation ("type text", "click mouse", "automate keyboard") --
        elif any(w in user_lower for w in ["type text", "type ", "click mouse", "automate keyboard", "move mouse"]):
            auto_res = jarvis_tools.keyboard_mouse_automation("TYPE", target="Active_Window", value=user_message)
            executed_tools.append({"tool": "keyboard_mouse_automation", "result": auto_res})

        # -- Tool 6: File & Folder Management ("list files", "read file", "create file") --
        elif any(w in user_lower for w in ["list files", "ls /home/user", "read file", "create file", "delete file"]):
            file_res = jarvis_tools.file_manager("list", ".")
            executed_tools.append({"tool": "file_manager", "result": file_res})

        # -- Tool 7: AI Coding Assistant ("write python code", "generate react code", "code for") --
        elif any(w in user_lower for w in ["write python", "write react", "write code", "generate python", "generate react", "coding assistant"]):
            lang = "python"
            if "react" in user_lower or "javascript" in user_lower or "jsx" in user_lower:
                lang = "react"
            code_res = jarvis_tools.ai_coding_assistant(lang, user_message)
            executed_tools.append({"tool": "ai_coding_assistant", "result": code_res})

        # -- Tool 8: System Telemetry ("cpu", "ram", "memory", "status", "diagnostic", "telemetry") --
        elif any(w in user_lower for w in ["cpu", "ram", "memory", "status", "diagnostic", "system check", "telemetry", "how are you running"]):
            telemetry_data = automation_engine.get_system_telemetry()
            executed_tools.append({
                "tool": "get_system_telemetry",
                "result": {
                    "cpu_percent": telemetry_data["cpu"]["percent"],
                    "memory_percent": telemetry_data["memory"]["percent"],
                    "uptime": telemetry_data["uptime"],
                    "os": telemetry_data["os"]
                }
            })

        # -- Tool 9: Time & Weather check --
        elif any(w in user_lower for w in ["time", "date", "weather", "temperature", "forecast", "what day"]):
            weather_data = automation_engine.get_time_and_weather()
            executed_tools.append({"tool": "get_time_and_weather", "result": weather_data})

        # -- Tool 10: Remember fact --
        remember_match = re.search(r"remember (?:that )?my (.+?) is (.+)", user_message, re.IGNORECASE)
        if remember_match:
            key = remember_match.group(1).strip().title()
            val = remember_match.group(2).strip()
            fact_res = memory_bank.remember_fact(key, val, category="user_preference")
            executed_tools.append({"tool": "remember_fact", "result": fact_res})
            memory_updates.append(fact_res)

        # -- Tool 11: Recall facts --
        if any(w in user_lower for w in ["who am i", "what do you remember", "my name", "what is my", "recall"]):
            facts = memory_bank.get_all_facts()
            executed_tools.append({"tool": "recall_facts", "result": {"count": len(facts), "facts": facts[:5]}})

        # -- Tool 12: Run Shell Command --
        if user_lower.startswith(("run ", "exec ", "terminal ", "command ")) or any(w in user_lower for w in ["ls -la", "df -h", "free -h", "uptime"]):
            cmd_str = re.sub(r"^(run|exec|terminal|command|execute)\s+(command\s+)?", "", user_message, flags=re.IGNORECASE).strip()
            if cmd_str:
                cmd_res = automation_engine.run_safe_shell_command(cmd_str)
                executed_tools.append({"tool": "run_shell_command", "result": cmd_res})

        # Generate Response
        response_text = ""
        if engine_to_use == "openai" and settings.OPENAI_API_KEY:
            response_text = self._generate_openai_response(user_message, executed_tools)
        elif engine_to_use == "ollama":
            response_text = self._generate_ollama_response(user_message, executed_tools)
        else:
            response_text = self._generate_jarvis_local_response(user_message, executed_tools)

        memory_bank.log_message("assistant", response_text)
        fresh_telemetry = automation_engine.get_system_telemetry()

        return {
            "response_text": response_text,
            "engine_used": engine_to_use,
            "executed_tools": executed_tools,
            "memory_updates": memory_updates,
            "telemetry": fresh_telemetry,
            "timestamp": time.time()
        }

    def _generate_jarvis_local_response(self, user_message: str, executed_tools: List[Dict[str, Any]]) -> str:
        user_lower = user_message.strip().lower()
        user_title = settings.USER_NAME

        if executed_tools:
            tool_summaries = []
            for t in executed_tools:
                t_name = t["tool"]
                t_res = t["result"]
                if t_name == "generate_ai_image":
                    tool_summaries.append(f"I have rendered your requested AI image for '{t_res['prompt']}', {user_title}. The visual artifact is displayed on screen.")
                elif t_name == "generate_document":
                    tool_summaries.append(f"Document Forge complete, {user_title}. Created {t_res['doc_type'].upper()} file titled '{t_res['title']}'. Download link is active.")
                elif t_name == "web_search_research":
                    tool_summaries.append(f"Web research concluded for '{t_res['query']}', {user_title}. Retrieved {t_res['count']} open-web briefings.")
                elif t_name == "desktop_app_control":
                    tool_summaries.append(f"Desktop Application protocol: {t_res.get('message', 'App command dispatched')}")
                elif t_name == "keyboard_mouse_automation":
                    tool_summaries.append(f"Keyboard & Mouse automation sequence executed for target '{t_res['target']}'.")
                elif t_name == "file_manager":
                    tool_summaries.append(f"File system scan of /home/user complete: {len(t_res.get('items', []))} items listed.")
                elif t_name == "ai_coding_assistant":
                    tool_summaries.append(f"AI Coding module generated modular {t_res['language'].upper()} script for '{t_res['prompt']}'.")
                elif t_name == "get_system_telemetry":
                    tool_summaries.append(f"System diagnostics are optimal, {user_title}. CPU load is at {t_res['cpu_percent']}%, memory is at {t_res['memory_percent']}%, and uptime is {t_res['uptime']}.")
                elif t_name == "get_time_and_weather":
                    tool_summaries.append(f"Current time: {t_res['datetime']}. External conditions in {t_res['location']}: {t_res['weather']}.")
                elif t_name == "remember_fact":
                    tool_summaries.append(f"Fact permanently logged into SQLite memory banks, {user_title}: {t_res['key']} = '{t_res['value']}'.")
                elif t_name == "recall_facts":
                    facts_str = ", ".join([f"{f['key']}: {f['value']}" for f in t_res["facts"]])
                    tool_summaries.append(f"Accessing long-term memory, {user_title}. Active protocols: {facts_str}.")
                elif t_name == "run_shell_command":
                    tool_summaries.append(f"Terminal command output:\n```\n{t_res['output'][:500]}\n```")
            return "\n\n".join(tool_summaries)

        if any(w in user_lower for w in ["who are you", "what can you do", "help", "capabilities", "introduce yourself"]):
            return (
                f"I am J.A.R.V.I.S. Mark II (v2.0.0), your Complete AI Desktop & Cloud Assistant. "
                f"I am equipped with 24 agentic protocols including Real-Time Voice & Wake Word ('Hey Jarvis'), "
                f"Camera Vision & Object Detection, AI Screen Understanding, App Opening/Closing, "
                f"Keyboard & Mouse Automation, AI Coding Assistant, File Management, AI Image Generation, "
                f"PDF Summarization, and Resume/PPT/Excel document generation."
            )

        if any(w in user_lower for w in ["hello", "hi ", "hey", "good morning", "good evening", "wake"]):
            return f"Good day, {user_title}. All 24 Mark II neural and desktop interfaces are online and operating at 100% capacity. How may I assist your projects?"

        if any(w in user_lower for w in ["thank you", "thanks", "good job"]):
            return f"Always a pleasure to be of service, {user_title}."

        return (
            f"I have processed your query regarding '{user_message}', {user_title}. "
            f"My Mark II neural networks, desktop automation hooks, and document forge are fully armed. "
            f"You may instruct me to generate documents, render images, inspect vision feeds, or execute desktop scripts."
        )

    def _generate_openai_response(self, user_message: str, executed_tools: List[Dict[str, Any]]) -> str:
        try:
            headers = {"Authorization": f"Bearer {settings.OPENAI_API_KEY}", "Content-Type": "application/json"}
            system_prompt = f"You are J.A.R.V.I.S. Mark II, Tony Stark's AI assistant. Speak as an articulate British butler to {settings.USER_NAME}. Tools executed: {json.dumps(executed_tools)}."
            payload = {"model": settings.OPENAI_MODEL, "messages": [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_message}], "temperature": 0.7}
            with httpx.Client(timeout=15.0) as client:
                res = client.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload)
                res.raise_for_status()
                return res.json()["choices"][0]["message"]["content"]
        except Exception as e:
            return f"OpenAI Neural Link latency ({str(e)}), Sir. Engaging Mark II NLP: " + self._generate_jarvis_local_response(user_message, executed_tools)

    def _generate_ollama_response(self, user_message: str, executed_tools: List[Dict[str, Any]]) -> str:
        try:
            url = f"{settings.OLLAMA_BASE_URL.rstrip('/')}/api/generate"
            prompt = f"You are J.A.R.V.I.S. Mark II, Tony Stark's AI assistant. Speak politely as a loyal British butler to {settings.USER_NAME}. Tools executed: {json.dumps(executed_tools)}. User query: {user_message}\nJ.A.R.V.I.S.:"
            payload = {"model": settings.OLLAMA_MODEL, "prompt": prompt, "stream": False}
            with httpx.Client(timeout=15.0) as client:
                res = client.post(url, json=payload)
                res.raise_for_status()
                return res.json().get("response", "").strip()
        except Exception as e:
            return f"Local Ollama Core unreachable ({str(e)}), Sir. Engaging standby Mark II NLP: " + self._generate_jarvis_local_response(user_message, executed_tools)

ai_engine = AIEngine()
